"""create taskflow users

Revision ID: 7d19c12c1fca
Revises: 
Create Date: 2026-09-09 08:55:21.981955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d19c12c1fca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskflow_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskflow_users_email'), 'taskflow_users', ['email'], unique=True)
    op.create_index(op.f('ix_taskflow_users_id'), 'taskflow_users', ['id'], unique=False)
    op.create_index(op.f('ix_taskflow_users_username'), 'taskflow_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskflow_users_username'), table_name='taskflow_users')
    op.drop_index(op.f('ix_taskflow_users_id'), table_name='taskflow_users')
    op.drop_index(op.f('ix_taskflow_users_email'), table_name='taskflow_users')
    op.drop_table('taskflow_users')
    # ### end Alembic commands ###
