"""add roles and update users

Revision ID: fc449d0a7970
Revises: 7d19c12c1fca
Create Date: 2026-09-09 21:43:02.601587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc449d0a7970'
down_revision: Union[str, Sequence[str], None] = '7d19c12c1fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskflow_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskflow_roles_id'), 'taskflow_roles', ['id'], unique=False)
    op.create_index(op.f('ix_taskflow_roles_name'), 'taskflow_roles', ['name'], unique=True)
    op.add_column('taskflow_users', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('taskflow_users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('taskflow_users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_taskflow_users_username'), table_name='taskflow_users')
    op.create_foreign_key(None, 'taskflow_users', 'taskflow_roles', ['role_id'], ['id'])
    op.drop_column('taskflow_users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskflow_users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'taskflow_users', type_='foreignkey')
    op.create_index(op.f('ix_taskflow_users_username'), 'taskflow_users', ['username'], unique=True)
    op.drop_column('taskflow_users', 'role_id')
    op.drop_column('taskflow_users', 'created_at')
    op.drop_column('taskflow_users', 'name')
    op.drop_index(op.f('ix_taskflow_roles_name'), table_name='taskflow_roles')
    op.drop_index(op.f('ix_taskflow_roles_id'), table_name='taskflow_roles')
    op.drop_table('taskflow_roles')
    # ### end Alembic commands ###
